[package]
name = "sway-prop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
serde = "1.0.171"
serde_json = "1.0.100"
swayipc = "3.0.1"
swayipc-types = "1.3.0"
