[package]
name = "nvru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
libc = "0.2.144"
neovim-lib = "0.6.1"
